### ISSUE TITLE
How to read custom properties from gopherbot.yaml

### ISSUE THREAD

**Issue by pasali** [lnxjedi/gopherbot#1]
Let say i defined a property like this:
```yml
Github:
  Token: "XXXxXXXXXX"
```
How can i read this property from gopherbot.yaml ? Or is there any other way to do this ?

**Comment by parsley42** [comment]
There's no facility for loading custom config from gopherbot.yaml(*), but you can load custom plugin configuration from conf/plugins/\<pluginname\>.yaml. goplugins/meme uses this, and also the sample ruby and powershell plugins. For example, conf/plugins/meme.yaml might have:
```yaml
Config:
  Username: 'me@my.dom'
  Password: 'aprettylousypassword'
```
... and the meme plugin can access that with the robot's GetPluginConfig() method. See the rubydemo and psdemo plugins for usage of GetPluginConfig. If I get some time later today, I might go ahead and write the API documentation for that. FYI, the most up-to-date documentation (though incomplete) is in the wiki.

(*) elevator, connector and brain plugins can read custom config from gopherbot.yaml

**Comment by pasali** [comment]
I read the Docs and was aware of plugin configuration. But what if more than one plugin use the same config ? What should i do for such a case? Should i define a general configuration file under `conf` directory and use it from all plugins that need it?

**Comment by parsley42** [comment]
Yes, I have a similar situation. My solution is to create e.g. common.yaml that has `Config:`, then create symlinks plugin1.yaml, plugin2.yaml etc.

**Comment by pasali** [comment]
Okay, i will do the same. Thanks for the answer.
