### ISSUE TITLE
Adding attachments to messages

### ISSUE THREAD

**Issue by pasali** [lnxjedi/gopherbot#10]
It would be very useful to add attachment. In my case, bot generates a config file for the user and i want  to reply with file as a attachment.

**Comment by parsley42** [comment]
Meaning, you want the bot to send an attachment to the user, or you want the user to be able to send attachments to the bot?

Attachment handling is something I'd definitely like to see, and have a real use case for. Problem is I have a number of much higher priority projects right now, so probably won't get to coding it for a while. Never hurts, though, to come up with a good design well ahead of coding. ;-)

**Comment by pasali** [comment]
I meant bot to user. Actually i have very good real world case. I am trying
to generate vpn config files via slack bot. So bot should be able to sent
back generated file to user. And i also have pretty tight schedule :)

25 Eki 2017 Çar, saat 17:50 tarihinde David Parsley <
notifications@github.com> şunu yazdı:

**Comment by pasali** [comment]
Hi @parsley42, any news on this one ? :)

**Comment by parsley42** [comment]
You should be able to accomplish this with the new version 2 code. It hasn't been released yet, pending documentation and tests, but it's more stable than 1.x, and I'm building [Docker images](https://cloud.docker.com/u/lnxjedi/repository/docker/lnxjedi/gopherbot) for it; you could just replace the gopherbot binary with your own build (if you're a docker shop). For your use case with Go plugins, not a lot has changed, but the [Robot object](https://godoc.org/github.com/lnxjedi/gopherbot/bot#Robot) now has a [ConnectorMessage](https://godoc.org/github.com/lnxjedi/gopherbot/bot#ConnectorMessage) attached, which includes the raw message object (as before) and Slack client. You can just use a type assertion to get the *slack.Client, and use the library to directly send a message using [MsgOptionAttachments](https://godoc.org/github.com/nlopes/slack#MsgOptionAttachments).

Right now I have no other plans for further support of attachments - we primarily use Gopherbot for CI/CD pipelines and scheduled jobs, with a little bit of interactive infrastructure management. Hopefully this will work for you.

**Comment by pasali** [comment]
Thats works for me. Thanks for the feedback. I just upgraded verision 2 but something is broken i guess. Bot is typing but never send message to slack. Here is the logs for command:
    
    2019/03/22 17:42:30 Debug: Message 'ping' from user 'pasali' in channel 'deploy'; 
    isCommand: true 
    2019/03/22 17:42:30 Debug: Unmatched command sent to robot, calling catchalls: ping
    2019/03/22 17:42:30 Debug: Unmatched command to robot and no catchall defined

**Comment by parsley42** [comment]
Ahhh, sorry - in version 1.x, a lot of plugin configuration was compiled in to the binary; in v2, it's all external, so you'll need to grab the distribution tarball and replace the binary with your own. When you start the `gopherbot` process:
* The process working directory (start directory) should be the root of _your_ configuration directory, which contains e.g. your `conf/gopherbot.yaml` and any external plugin configs; most likely you just have `conf/gopherbot.yaml` with your slack token
* The binary being run should be in the install directory, with e.g. `conf/` and `lib/` subdirectories. The default robot and plugin configuration is all in `conf/` now.

Simplest thing to do:
1. Untar latest gopherbot archive in /opt/gopherbot
1. Replace /opt/gopherbot/gopherbot with _your_ binary
1. Create a symlink to your binary in the parent of your `conf/` directory w/ slack token
1. Run `./gopherbot` in that directory

The good news is, if you want to modify configuration for built-in plugins, you just `cp /opt/gopherbot/conf/plugins/<foo>.yaml /your/conf/plugins/<foo>.yaml` and edit the file.

If you have problems or other questions, feel free to just email parsley@linuxjedi.org directly, and I'll try to help get you up and running with version 2.

**Comment by pasali** [comment]
Thanks for answer. I managed to get things work again.

**Comment by parsley42** [comment]
Great, I'll go ahead and close this issue.
