### ISSUE TITLE
add gopherbot, normalize snapshot name/path, and folder name.

### ISSUE THREAD

**Issue by cornexo** [lnxjedi/gopherbot#203]
Used to untar to `gopherbot` and now `gopherbot-2.0.0-beta4-snapshot`.

Also snapshot location changed from `https://github.com/lnxjedi/gopherbot/releases/download/v2.0.0-beta4-snapshot/gopherbot-linux-amd64.tar.gz` and now `https://github.com/lnxjedi/gopherbot/archive/v2.0.0-beta4-snapshot.tar.gz`

**Comment by cornexo** [comment]
Also missing gopherbot executable.

**Comment by parsley42** [comment]
This turned out to be an issue with the new release not being published properly. The publish binary needs to do a better job of deleting the old tag.

**Comment by parsley42** [comment]
For the time being at least, Gopherbot has changed to container distribution only with build-from-source instructions. Closing this issue.
