### ISSUE TITLE
How to add a endpoint on Bot

### ISSUE THREAD

**Issue by pasali** [lnxjedi/gopherbot#3]
I want to add a callback endpoint on Bot. How can i achieve this ?

**Comment by parsley42** [comment]
There's no generic support for callbacks yet, and currently none planned, but you could write a Go plugin for this. When gopherbot starts the connector or does a reload, it calls each plugin with the command "init". In the processing for init, you'd check to see if your http listener is already running (in the case of a reload), and then fire off a goroutine with the bot object that would create a listener.

**Comment by pasali** [comment]
i created listener on main.go like this: 
```go
go func() {
		http.Handle("/metrics", handler)
                http.ListenAndServe(":8080", nil)
	}()
``` 
İs this a bad practice ? Should i really need a plugin for this?

**Comment by parsley42** [comment]
I don't have any problem with this, if it works for you. The main reason to do it in a plugin would be getting the robot object from init, and storing it so you could later use one of the "Send*Message" methods, and also to store stuff in the brain, etc. If you're just adding the listener in main, how is your handler interacting with the robot?

**Comment by pasali** [comment]
I understand what you mean but i don't interact with bot directly. So it works for me this way. Thanks for reply.
