### ISSUE TITLE
How to mention a specific user

### ISSUE THREAD

**Issue by pasali** [lnxjedi/gopherbot#4]
Is there any way to mention a user other than who calls bot ? For example hubot's encourage command, you can pass a bot something like this `hubot encourage name` then it responds with mentioning target user.

**Comment by parsley42** [comment]
So, the Say() and Respond() methods just wrap the Send*Message() methods:
SendUserMessage(user, msg) - send a DM
SendUserChannelMessage(user, chan, msg) - direct the message to a user with a mention
SendChannelMessage(chan, msg) - send a message to a channel

SendUserChannelMessage(...) should do what you want?

**Comment by pasali** [comment]
Not exactly.I want to be able to format message with username. Basically what i want to do is something like that:
`I wish I was more like %s.` => template
`I wish I was more like @pasali.` how should bot reply

**Comment by parsley42** [comment]
Ah, ok - I took a look at the connector code, and any occurrence of "@somestring" becomes a mention. So all you need to do is insert the '@': "I wish I was more like @%s"

**Comment by pasali** [comment]
Yes, it works like a charm. Thanks again.
